name : My first workflow

on :
  push :
   branches : [main]

jobs :
   Show message:
      runs-on : ubutnu-latest
       
      steps:
         - name : Display
           run : echo "HELLO THIS IS MY FIRST WORKFLOW "